<?php
/*
* Implement hook_cron()
*/
function heartmonitor_cron() {
  // Get last report log for 404 page (with 'ping-from-home')  timestamp in watchdog table
  $last_404_time = db_query("SELECT timestamp FROM {watchdog} WHERE type='page not found' AND  message LIKE '%ping-from-home%' ORDER BY timestamp DESC LIMIT 1")->fetchField();

  // Run code if there is data
  if($last_404_time) {
    // add cron time to the queried timestamp in report log to get due time
    // cron time is a predetermine value
    $due_time = strtotime('+10 minutes', $last_404_time);
    $curr_time = time(); // get current time

    // if current time is more than the due time, send email to notify the admin
    if($curr_time > $due_time) {
      drupal_mail('heartmonitor', 'heartmonitor_email', 'systems@joineryhq.com', language_default());
    }
  }
}

/*
* Implement hook_mail()
* messages to notify the admin
*/
function heartmonitor_mail($key, &$message, $params) {
  switch($key) {
    case 'heartmonitor_email':
      $message['subject'] = t('Joinery Heartbeat Monitor notification');
      $message['body'][]  = t('This is an email from the site @site-name', array('@site-name' => variable_get('site_name','localhost')));
      $message['body'][]  = t('The backup failed. Please check the site.');

      break;
  }
}
